puppeteer-extra-plugin-recaptcha: Filtering by whether the iframe is visible to the user, instead of using src
berstend/puppeteer-extra pull request #304
Opened 2020-08-31 19:24 UTC by bclougherty

This PR fixes #300 

Captchas with 'invisible' in the src can be shown via js, at which point the plugin fails to find them.

My patch uses something equivalent to jquery's `is(':visible')` to check whether the captcha is visible to the user, rather than relying on the src value.

2020-09-01 04:29 UTC, berstend requested changes
@bclougherty sweet!

there's what looks like a linting issue according to the test runner, could you fix that? :-)

```bash
src/content.ts:32:161 - error TS1005: ';' expected.

32   private _isVisible = (elem: any) => !!( elem.offsetWidth || elem.offsetHeight || (typeof elem.getClientRects === 'function' && elem.getClientRects().length )))
                                                                                                                                                                   ~


Found 1 error.
```

2020-09-01 13:26 UTC, bclougherty commented
@berstend Sorry about that, had a couple stray characters in there. It should be good now.

2020-09-01 19:45 UTC, Niek approved these changes

2020-09-02 11:17 UTC, berstend approved these changes

2020-09-02 11:17 UTC, merged

2020-09-02 11:22 UTC, berstend commented
Published as `puppeteer-extra-plugin-recaptcha@3.1.18` - thanks @bclougherty 👍