fix(recaptcha) findRecaptcha() does not wait indefinitely to timeout
berstend/puppeteer-extra pull request #558
Opened 2021-09-19 21:38 UTC by tanguc

findRecaptcha() does not wait indefinitely to timeout when not finding captchas

2021-09-23 16:59 UTC, berstend requested changes
@tanguc can you provide more context?

Your function signature doesn't match with the API:
https://github.com/puppeteer/puppeteer/blob/main/docs/api.md#pagewaitforfunctionpagefunction-options-args

2021-09-23 19:25 UTC, tanguc commented
> 
> 
> @tanguc can you provide more context?
> 
> Your function signature doesn't match with the API:
> https://github.com/puppeteer/puppeteer/blob/main/docs/api.md#pagewaitforfunctionpagefunction-options-args

I did see the `Page` type was coming from Puppeteer's one, on my side I was talking about https://playwright.dev/docs/api/class-page#page-wait-for-function

The second arg is the arg(s) which will be given to the first arg (function)

Now, how should we deal with that now ?

2021-09-25 15:07 UTC, berstend commented
@tanguc can you describe the problem you're trying to solve? The code you modified is just convenience in case the developer immediately called `page.findRecaptcha()`, before the page has fully loaded yet.

If you're experiences timeout related issues you could also just wait for the page to be fully loaded (or even the captcha iframe to appear in the DOM) before calling the recaptcha plugin?

2021-09-25 15:08 UTC, berstend commented
> findRecaptcha() does not wait indefinitely to timeout when not finding captchas

We don't want to wait indefinitely, as otherwise calling `page.solveRecaptchas()` on a page without captchas would never return

2021-09-25 20:21 UTC, tanguc commented
> 
> 
> @tanguc can you describe the problem you're trying to solve? The code you modified is just convenience in case the developer immediately called `page.findRecaptcha()`, before the page has fully loaded yet.
> 
> If you're experiences timeout related issues you could also just wait for the page to be fully loaded (or even the captcha iframe to appear in the DOM) before calling the recaptcha plugin?

I'm already calling `page.findRecaptcha()` only after I did wait the network to idle 
However in the case where the page do not contain any captcha it will indefinitely wait, and in my case I'm using playwright behind as well as the `Page`, the playwright's signature `https://playwright.dev/docs/api/class-page#page-wait-for-function` one is completely different from the Puppeteer's one

2021-12-16 12:10 UTC, no4nou commented
при использовании Xevil дает ошибку Error: 2captcha error: XEVIL INTERNAL ERROR: PROBABLY, INCORRECT REQUEST

2022-06-20 14:28 UTC, closed without merging